blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/shopperlabs/shopper/issues/new
    about: Submit a bug or an issue
  - name: Feature request
    url: https://github.com/shopperlabs/shopper/discussions/new
    about: For ideas or feature requests
  - name: Support questions & other
    url: https://github.com/shopperlabs/shopper/discussions/new
    about: If you have a question or need help using the framework
  - name: Discord
    url: https://laravelshopper.dev/discord
    about: For quick help, ask questions in the appropriate channel
