<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Mailables Directory
    |--------------------------------------------------------------------------
    |
    | This directory is generated by Laravel when creating a mailable class
    |
    */

    'mailables_dir' => app_path('Mail/'),

    /*
    |--------------------------------------------------------------------------
    | Environment
    |--------------------------------------------------------------------------
    |
    | If you don't want to use this package in production env at all, you
    | can restrict that using this option rather than by using a middleware.
    |
    */

    'allowed_environments' => ['local', 'staging', 'testing'],

    /*
    |--------------------------------------------------------------------------
    | Templates
    |--------------------------------------------------------------------------
    |
    | List of pre-defined templates used by maileclipse (HTML/Markdown)
    | @see https://github.com/Qoraiche/laravel-mail-editor
    |
    */

    'skeletons' => [

        'html' => [

            'airmail' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'cerberus' => [
                'fluid',
                'hybrid',
                'responsive',
            ],

            'cleave' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'go' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'goldstar' => [
                'birthday',
                'confirm',
                'invite',
                'invoice',
                'progress',
                'reignite',
                'survey',
                'update',
                'welcome',
            ],

            'mantra' => [
                'activation',
                'birthday',
                'coupon',
                'progress',
                'rating',
                'receipt',
                'shipped',
                'update',
                'welcome',
            ],

            'meow' => [
                'confirmation',
                'coupon',
                'digest-left',
                'digest-right',
                'progress',
                'receipt',
                'survey',
                'two-column',
                'welcome',
            ],

            'narrative' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'neopolitan' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'oxygen' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'plain' => [
                'plain',
            ],

            'skyline' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'sunday' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

            'zenflat' => [
                'confirm',
                'invite',
                'invoice',
                'ping',
                'progress',
                'reignite',
                'survey',
                'upsell',
                'welcome',
            ],

        ],

        'markdown' => [
            'postmark' => [
                'blank',
                'comment-notification',
                'invoice',
                'receipt',
                'reset-password',
                'reset-password-help',
                'trial-expired',
                'trial-expiring',
                'user-invitation',
                'welcome',
            ],
        ],
    ],

];
