name: monorepo-split

on:
  push:
    branches:
      - '2.*'
    tags: '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - admin
          - core
          - sidebar
    steps:
      - uses: actions/checkout@v3
      - id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'shopperlabs'
          repository_name: '${{ matrix.package }}'
          branch: 2.x
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'Arthur Monney'
          user_email: 'contact@arthurmonney.me'
