name: npm-build

on:
  pull_request:
    branches:
      - '*.x'
    types:
      - closed

jobs:
  npm-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: 2.x
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore: Build assets"
