name: Builds assets

on:
  pull_request:
    branches:
      - '*.x'
    types:
      - closed

jobs:
  npm-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install PHP & Npm dependencies
        run: |
          composer install --no-interaction
          npm ci
      - name: Build assets
        run: npm run build
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore: Build assets"
