name: "phpstan Static Analysis"

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1", "8.2"]
        laravel: ["^9.0", "^10.0"]
        dependencies: ["highest"]

    name: "PHP ${{ matrix.php }} - L${{ matrix.laravel }} ${{ matrix.dependencies == 'highest' && '↑' || '↓' }}"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          tools: "composer:v2"
          coverage: "none"

      - name: "Install dependencies from composer.json"
        if: "matrix.dependencies != 'lowest'"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress --prefer-lowest"

      - name: "Run PHPStan"
        run: ./vendor/bin/phpstan
