name: Pint

on:
  push:
    branches:
      - '*.x'
  pull_request:

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: |
          composer install --no-interaction
          npm ci
      - name: Run Rector
        run: composer test:refactor
      - name: Run Prettier
        run: npm run prettier
      - name: Run Laravel Pint
        run: composer test:lint
